[package]
name = "roll"
version = "0.1.0"
authors = ["Martin Kouba <mkouba@redhat.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.6"
regex = "1"
